slam_toolbox:
  ros__parameters:
    # 1. CORE ROS FRAMES (UPDATED FOR NAMESPACE)
    odom_frame: mouse/odom          # <--- Was 'odom'
    map_frame: map                  # Keep 'map' so it generates the global map
    base_frame: mouse/base_link     # <--- Was 'base_link'
    scan_topic: /mouse/scan         # <--- Was '/scan'
    mode: mapping 

    # 2. SOLVER (The Math)
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # 3. PERFORMANCE TUNING
    debug_logging: false
    throttle_scans: 1
    transform_publish_period: 0.02
    map_update_interval: 0.5
    resolution: 0.05
    max_laser_range: 8.0 
    minimum_time_interval: 0.1
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    stack_size_to_use: 40000000 
    enable_interactive_mode: true
    
    # 4. MATCHING
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.1
    minimum_travel_heading: 0.1
    scan_buffer_size: 10
    scan_queue_size: 10
    link_match_minimum_response_fine: 0.1  
    link_scan_maximum_distance: 1.5
    loop_search_maximum_distance: 3.0
    do_loop_closing: true 
    loop_match_minimum_chain_size: 10           
    loop_match_maximum_variance_coarse: 3.0  
    loop_match_minimum_response_coarse: 0.35    
    loop_match_minimum_response_fine: 0.45